;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mode-line-minor-mode-help
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        buffer-menu
        kill-region
        mouse-minor-mode-menu
        ))
